const THUNK_ACTIONS = {
  AUTH_USER: "USER/AUTH_USER",
  MODAL_CLOSE: "MODAL/CLOSE_MODAL",
  PROFILE_CHANGE_INFO: "PROFILE/CHANGE_INFO",
  PROFILE_CHANGE_PASSWORD: "PROFILE/CHANGE_PASSWORD",
  PROFILE_CHANGE_PHOTO: "PROFILE/CHANGE_PHOTO",
  GET_PRODUCTS: "PRODUCTS/GET_PRODUCTS",
  GET_TOP_PRODUCTS: "PRODUCTS/GET_TOP_PRODUCTS",
  SEARCH_PRODUCTS: "PRODUCTS/SEARCH_PRODUCTS",
  UPDATE_PRODUCT: "PRODUCTS/UPDATE_PRODUCT",
  CREATE_PRODUCT: "PRODUCTS/CREATE_PRODUCT",
  DELETE_PRODUCT: "PRODUCTS/DELETE_PRODUCT",
};

export default THUNK_ACTIONS;
