const SAGA_ACTIONS = {
  AUTH_USER: "USER/AUTH_USER_SAGA",
  MODAL_CLOSE: "MODAL/CLOSE_MODAL_SAGA",
  PROFILE_CHANGE_INFO: "PROFILE/CHANGE_INFO",
  PROFILE_CHANGE_PASSWORD: "PROFILE/CHANGE_PASSWORD",
  PROFILE_CHANGE_PHOTO: "PROFILE/CHANGE_PHOTO",
  GET_PRODUCTS: "PRODUCTS/GET_PRODUCTS",
};

export default SAGA_ACTIONS;
